---
title: "comparison"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{comparison}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
<div style="font-size: 20px; color: black; line-height: 1.5;"> This is a comparison between lmr() function from jyzlmr and lm() from original function </div>

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
----------------------------------------------------------------

```{r setup}

library(jyzlmr)
data=mtcars
result <- lmr("mpg", "wt + hp + qsec", data)



# Run lmr function
start_time <- Sys.time()
lmr_result <- lmr("mpg", "wt + hp + qsec", data)
lmr_time <- Sys.time() - start_time
print(lmr_result)

# Compare with lm function
start_time <- Sys.time()
lm_model <- lm(mpg ~ wt + hp + qsec, data = data)
lm_time <- Sys.time() - start_time
lm_summary <- summary(lm_model)
print(lm_summary)


cat("lmr runtime:", lmr_time, "\n")
cat("lm runtime:", lm_time, "\n")


```

<div style="font-size: 20px; color: black; line-height: 1.5;"> We can see the result, All parameters are the same but lmr function is slower in terms of running efficiency  </div>
